# Generated by Django 5.2 on 2025-04-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_duration_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='Продолжительность (в неделях)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(verbose_name='Цена (в рублях)'),
        ),
    ]
